# Generated by Django 5.1.7 on 2026-01-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_cartitem_cart_add_cart_delete_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_cart',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
