# Generated by Django 5.1.7 on 2026-01-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_add_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_cart',
            name='image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_cart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='add_cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='add_cart',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
    ]
