# Generated by Django 5.1.7 on 2026-01-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_add_cart_image_alter_add_cart_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Cart',
        ),
    ]
