# Generated by Django 5.1.7 on 2026-01-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='details',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_cart',
            name='service_details',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
