# Generated by Django 5.1.7 on 2026-01-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_cart_details_add_cart_service_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Cart',
        ),
    ]
