# Generated by Django 5.1.7 on 2026-01-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_myorder_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='details',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='image',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='service_details',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='service_name',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='service_name',
            field=models.TextField(),
        ),
    ]
