# Generated by Django 5.1.7 on 2026-01-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_orderfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderFeedback',
        ),
    ]
