# Generated by Django 5.1.7 on 2026-01-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_orderfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='MyOrder',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
