# Generated by Django 5.1.7 on 2026-01-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_ordercomplaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderComplaint',
        ),
    ]
