# Generated by Django 5.1.7 on 2026-02-01 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_servicecenterregister'),
        ('users', '0031_ordercomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='service_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.servicecenterregister'),
        ),
        migrations.AddField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
