# Generated by Django 5.1.7 on 2026-02-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_myorder_service_center_myorder_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderFeedback',
        ),
    ]
