# Generated by Django 5.1.7 on 2026-02-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
