# Generated by Django 5.1.7 on 2026-02-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Cart',
        ),
    ]
