# Generated by Django 5.1.7 on 2026-02-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_add_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
