# Generated by Django 5.1.7 on 2026-02-08 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField()),
                ('service_details', models.TextField()),
                ('details', models.TextField()),
                ('extra_details', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image', models.URLField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.myorder')),
            ],
        ),
    ]
