# Generated by Django 5.1.7 on 2026-02-14 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0043_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_center_id', models.IntegerField()),
                ('old_image', models.ImageField(upload_to='service_old/')),
                ('new_image', models.ImageField(upload_to='service_new/')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.myorder')),
            ],
        ),
    ]
