# Generated by Django 5.1.7 on 2026-01-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_popularbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularbooking',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
