# Generated by Django 5.1.7 on 2026-01-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_product_servicedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serviceDetails',
            field=models.TextField(null=True),
        ),
    ]
