# Generated by Django 5.1.7 on 2026-01-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_advertisement_advertisement1_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCenterRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('servicecenter_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('aadhaar', models.CharField(max_length=12, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
