# Generated by Django 5.1.7 on 2026-02-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_servicecenterregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
