# Generated by Django 5.1.7 on 2026-02-08 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_watercoolerservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='laptop_services/')),
                ('service_details', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('link', models.URLField(max_length=500)),
                ('details', models.TextField()),
                ('extra_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
