# Generated by Django 5.1.7 on 2026-02-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_fridgeservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
