# Generated by Django 5.1.7 on 2026-02-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
